# This is a basic workflow to help you get started with Actions
on:
  workflow_dispatch:
  schedule:
    - cron: '* * 2 * *' # Runs every 3rd of the Month

jobs:
  build-pages:
    runs-on: ubuntu-20.04
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        persist-credentials: false
        token: ${{ secrets.GH_API_TOKEN }}
    - name: download wiktext
      env: 
       COMMITTEXT: "${{ github.event.head_commit.message }}"
      run: |
         ./try_download.sh
