# This is a basic workflow to help you get started with Actions
on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 1 * *' # Runs every 3rd of the Month

jobs:
  build-pages:
    runs-on: ubuntu-20.04
    
    steps:
    - name: Checkout code
      uses: actions/checkout@master
    - name: download jq
      uses: sergeysova/jq-action@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: download wiktext pronunciations
      run: |
         curl "https://kaikki.org/dictionary/raw-wiktextract-data.json" | jq --raw-output -c '. | select(.lang_code=="en")? | {related: .related, derived: .derived, forms: .forms, pos: .pos, head_templates: .head_templates, senses: .senses, etymology_text: .etymology_text, sounds: .sounds}' | perl -ne 'use Digest::MD5 qw(md5_base64); print unless $seen{md5_base64($_)}++' | python ./check_chars.py | 7z a -t7z -m0=lzma -mx=9 -mfb=64 -md=32m -ms=o -si wiki_dict.json.7z
    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        author_name: wiktext-pron-adder-bot
        author_email: ""
        message: "updated wiki_dict.json.gz"
        add: wiki_dict.json.gz
