# This is a basic workflow to help you get started with Actions
on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 1 * *' # Runs every 3rd of the Month

jobs:
  build-pages:
    runs-on: ubuntu-20.04
    
    steps:
    - name: Checkout code
      uses: actions/checkout@master
    - name: download jq
      uses: sergeysova/jq-action@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: download wikipedia word frequencies, and wikitext etymologies / pos
      timeout-minutes: 780
      run: |
        python -m pip install lxml
        python make_wikidict_online.py <(curl "https://dumps.wikimedia.org/enwiki/latest/enwiki-latest-pages-articles.xml.bz2" ) wiki_dict
        curl "https://kaikki.org/dictionary/raw-wiktextract-data.json" | \
          jq --raw-output -c '. | select(.lang_code=="en")? | {word: .word, related: .related, derived: .derived, forms: .forms, pos: .pos, senses: .senses, etymology_text: .etymology_text, sounds: .sounds}' | \
          perl -ne 'use Digest::MD5 qw(md5_base64); print unless $seen{md5_base64($_)}++' | \
        python ./check_chars.py <(awk -F " " '{if ($2>20) {print $1} }' wiki_dict ) > etymologies.json
    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        author_name: wiki-etymology-adder-bot
        author_email: ""
        message: "updated etymologies.json"
        add: etymologies.json
