# This is a basic workflow to help you get started with Actions
on:
  workflow_dispatch:
  schedule:
    - cron: '* * 2 * *' # Runs every 3rd of the Month

jobs:
  build-pages:
    runs-on: ubuntu-20.04
    
    steps:
    - name: Checkout code
      uses: actions/checkout@master
    - name: download jq
      uses: sergeysova/jq-action@v2
    - name: download wiktext
      run: |
         curl "https://kaikki.org/dictionary/raw-wiktextract-data.json" | jq -a -s -c '. | select(.lang_code=="en")? | { word: .word, related: .related, derived: .derived, forms: .forms, categories: .categories, pos: .pos, head_templates: .head_templates, senses: .senses, etymology_text: .etymology_text, etymology_templates: .etymology_templates}' > kaikki_wiki_dict.json
