# This is a basic workflow to help you get started with Actions
on:
  workflow_dispatch:
  schedule:
    - cron: '* * 2 * *' # Runs every 3rd of the Month

jobs:
  build-pages:
    runs-on: ubuntu-20.04
    
    steps:
    - name: Checkout code
      uses: actions/checkout@master
    - name: download jq
      uses: sergeysova/jq-action@v2
    - name: download wiktext
      run: |
         curl "https://kaikki.org/dictionary/raw-wiktextract-data.json" | jq --raw-output -c '. | select(.lang_code=="en")? | .word as $WORD | .sounds[]  | select(.ipa != null and (select(.tags[] == "UK") or select(.tags == "Received-Pronunciation")) ) | del(.tags) | {ipa:.ipa, tags:.tags, word:$WORD}' | jq -r '[.word,.ipa] | @tsv' | awk -F $"\t" '!/^.*(\[.*\]|\-)$|[A-Z][A-Z]+/' | sed -r -e 's/\(É¹\)//g;s/\.|\/|\(|\)//g' | grep -Pv "\-$" > en-GB_wiki_dict.tsv
